version: '3.8'

services:
  php:
    build:
      context: ./.docker
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/symfony
    depends_on:
      - database
      - cache

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/var/www/symfony
      - ./path/to/your/nginx/conf:/etc/nginx/conf.d
    depends_on:
      - php

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

  cache:
    image: redis:latest
    volumes:
      - cache_data:/data

volumes:
  db_data:
  cache_data:
